version: '3'
services:
  line-notify:
    container_name: line-notify
    build: .
    image: ses2/node:8-axios
    environment:
      - LINE_TOKEN=$LINE_TOKEN
    tty: true
    volumes:
      - ./app:/app
